<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="UTF-8" />

        <?php echo $this->headTitle('Pasajesterrestres ' . $this->translate('Tu terminal virtual'))->setSeparator(' - ')->setAutoEscape(false); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'icon', 'sizes' => '16x16 32x32 48x48 64x64', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
        ->prependStylesheet($this->basepath() . '/css/magnific-popup.css')
        ->prependStylesheet($this->basePath() . '/css/main.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/js/libs/datetimepicker-master/jquery.datetimepicker.css');
//         ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css')
//         ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css');
//                         ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
//                         ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/jquery.magnific-popup.js')
            ->prependFile($this->basePath() . '/js/libs/jquery.autocomplete.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/libs/datetimepicker-master/jquery.datetimepicker.js')
            ->prependFile('http://code.jquery.com/ui/1.9.2/jquery-ui.js')
//             ->prependFile($this->basePath() . '/js/libs/jquery-ui-1.11.4/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/js/libs/jquery-2.1.3.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',));
        ?>
    </head>
    <body>
        <section class="main-container">

            <!--START MAIN CONTENT -->
            <div class="main-content general-forms login-form">
                <?php echo $this->content; ?>
            </div>
            <!--END MAIN CONTENT -->

            <?php echo $this->inlineScript(); ?>
<!--            <script src="../js/libs/jquery-2.1.3.min.js"></script> -->
            <script src="/js/libs/jquery.bxslider.min.js"></script>
            <script src="/js/customScript.js"></script>
            <script src="/js/auth.js"></script>
        </section>
    </body>
</html>
