<section class="travel-route-data">
	<h2 class="ttl-1">Guía de trayecto</h2>
	<div class="cont-travel-data">
		<div class="general-data">
			<div class="cont-map">
				<!-- Mapa Google Maps -->
			</div>
			<ul class="list-data">
				<li>
					<h2 class="txt-1">Distancia</h2>
					<h3 class="txt-2">407km</h3>
				</li>
				<li>
					<h2 class="txt-1">Tiempo estimado</h2>
					<h3 class="txt-2">8hrs 21min</h3>
				</li>
			</ul>
		</div>
		<div class="travel-route">
			<h2 class="txt-1">Recorrido:</h2>
			<ul class="list-route">
				<li>
					<?php echo $cityOrigen; ?>
				</li>
				<li>
					-
				</li>
				<li>
					-
				</li>
				<li>
					-
				</li>
				<li>
					<?php echo $cityDestino; ?>
				</li>
			</ul>
		</div>
	</div>
</section>