
Terminal virtual para la venta de tiquetes online.


QUINES SOMOS

Pasajes terrestres.com nace el 11 de agosto de 2014 con personería jurídica y matrícula mercantil No 02485216, aunque llevamos gestando la idea y realizando estudios desde el 6 de junio del 2012, ubicados en la terminal de transportes salitre, lo cual nos lleva a conocer más de cerca muchas situaciones del vivir diario de nuestros hermanos Colombianos, así como muchos extranjeros que vienen con el ánimo de conocer nuestro territorio nacional cultura, flora y fauna y toda la  belleza de nuestra nación.

Debido a las largas filas en las terminales de transporte que se convierten en un suplicio para los usuarios sin tener ninguna solución viable para adquirir su tiquete de viaje, tanto adultos como mujeres embarazadas y con niños en brazos, muchas de estas personas por su necesidad de llegar al punto de destino caen en las manos de los llamados reboletiadores quienes los convencen  para que viajen en un transporte informal arriesgando la  vida de estos pasajeros,  ya que este tipo de transporte con cuenta con los seguros, ni los permisos requeridos por la ley que aseguren la integridad de mismo, por lo tanto no los obligan a llevar al pasajero a su destino en los horarios y rutas acordadas ya que muchas veces los dejan en cualquier punto que ellos decidan, cobrándoles los tiquetes a su destino completo.

Es así como PASAJESTERRESTRES.COM  se crea para satisfacer las necesidades de los usuarios brindando seguridad, confianza y agilidad a la hora de viajar a cualquier destino nacional e internacional, con un alcance de cobertura masiva, con calidad, credibilidad y experiencia  comercial, contamos con el apoyo  de todas las empresas de servicio de transporte terrestre, un equipo de trabajo capacitado y  los recursos tecnológicos de avanzada para hacer de nuestro cliente un happy consumer.

MISION

PASAJES TERRESTRES.COM, es una compañía soportada en avances tecnológicos de última generación, implementando la evolución del servicio en el mercado de transporte terrestre de pasajeros a través de nuestra plataforma web, con el fin de

VISION

Nuestra Compañía proyecta ser la terminal virtual más importante del territorio nacional y Suramérica, basada en excelente servicio, con amplia gama de destinos y apoyados por la inclusión de empresas transportadoras nacionales e internacionales, convirtiéndose en la taquilla e-comerce preferida por los clientes.