<div class="weather-container">
	<ul class="weather-slider">
		<li>
			<p class="txt-city">
				Santa Marta, Magdalena
			</p>
<!-- 			<div class="weather-info"> -->
<!-- 				<p class="txt-1"> -->
<!-- 					<span class="icon-compass-arrow-1"></span>Bogot&aacute; -->
<!-- 				</p> -->
<!-- 				<p class="txt-2"> -->
<!-- 					12° -->
<!-- 				</p> -->
<!-- 				<p class="txt-1"> -->
<!-- 					Dom, 9:40 am -->
<!-- 				</p> -->
<!-- 			</div> -->
			<img src="/images/dummy-image-weather-bog.jpg" alt="">
		</li>
		<li>
			<p class="txt-city">
				Santa Marta, Magdalena
			</p>
<!-- 			<div class="weather-info"> -->
<!-- 				<p class="txt-1"> -->
<!-- 					<span class="icon-compass-arrow-1"></span>Bogot&aacute; -->
<!-- 				</p> -->
<!-- 				<p class="txt-2"> -->
<!-- 					12° -->
<!-- 				</p> -->
<!-- 				<p class="txt-1"> -->
<!-- 					Dom, 9:40 am -->
<!-- 				</p> -->
<!-- 			</div> -->
			<img src="/images/dummy-image-weather-bog.jpg" alt="">
		</li>
	</ul>
</div>